name: Docker Build and Push

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#VERSIONS
          - name: 3.13-alpine-glibc2.34-r0
            context: 3.13/alpine-glibc
            platforms: linux/amd64
            tags: |
              3.13-alpine-glibc
#VERSIONS
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sirmark/python
          tags: ${{ matrix.tags }}

      - uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
